#!/usr/bin/env python

from datetime import datetime;
from ConfigParser import SafeConfigParser;
import os;
import os.path;
import re;
import sys;

def main():
	config = os.environ.get('TMUX_VIM_CONFIG', '~/.tmux-vim.conf')
	load_config_file_to_environment(config)
	cp = create_config_from_environment()
	write_config(cp, sys.stdout)

def load_config_file_to_environment(filename):
	# Rather than try to parse the shell config file, exec the shell itself,
	# get it to parse the shell config file, and then call this script again.
	# That way all the stuff in the config file will then be in the environment.
	#
	# Use $TMUX_VIM_CONVERTING to flag that we've called ourselves.
	if '_TMUX_VIM_CONVERTING' not in os.environ:
		shell = os.environ['SHELL']
		shell_cmds = [
			'set -a',						# export all variables
			'source ' + filename, 			# read the config
			'_TMUX_VIM_CONVERTING=1',		# set the re-entry flag
			os.path.abspath(sys.argv[0])	# run this script again
		]
		# Call exec rather than system because we don't want to return
		os.execl(shell, shell, '-c', ';'.join(shell_cmds))

def parse_layout_section(cp, section, config):
	dconf = { }
	cp.add_section(section)
	for opt in config.split(','):
		key, value = opt.split(':')
		cp.set(section, key, value)
		dconf[key] = value;
	return dconf

def create_config_from_environment():
	cp = SafeConfigParser()

	env = os.environ
	cmd_section = 'commands'
	cp.add_section(cmd_section)
	if 'TMUX_VIM_TMUX_BIN' in env:
		cp.set(cmd_section, 'tmux', env['TMUX_VIM_TMUX_BIN'])
	else:
		cp.set(cmd_section, '# tmux', '(tmux commandline)')
	if 'TMUX_VIM_VIM_BIN' in env or 'TMUX_VIM_VIM_ARGS' in env:
		vim = env.get('TMUX_VIM_VIM_BIN', 'vim')
		if 'TMUX_VIM_VIM_ARGS' in env:
			vim += ' ' + env['TMUX_VIM_VIM_ARGS']
		cp.set(cmd_section, 'vim', vim)
	else:
		cp.set(cmd_section, '# vim', '(vim commandline)')

	layout = parse_layout_section(cp, 'layout', env.get('TMUX_VIM_LAYOUT', ''))

	# See if we can find any sub-layouts like in the sample config
	for var in env:
		match = re.match('TMUX_VIM_LAYOUT_(.*)', var)
		if match:
			name = match.group(1).lower()
			sub_layout = parse_layout_section(cp, 'layout=' + name, env[var])
			# See if our sub-layout matches any others
			if sub_layout == layout:
				cp.remove_section('layout')
				cp.add_section('layout')
				cp.set('layout', 'include', name)

	return cp

def write_config(cp, fh):
	print >> fh,  '# tmux-vim config'
	print >> fh,  '# automatically generated by %s at %s' % (os.path.basename(sys.argv[0]), datetime.now())
	print >> fh
	cp.write(sys.stdout)


if __name__ == "__main__":
	main()
