#!/bin/bash

#------------------------------------------------------------------------------
# tmux-vim
#
# Persistent vim panes within tmux.
#
# Usage:
#
#   tmux-vim [file [files...]]
#
# Configuration:
#
#   TMUX_VIM_ARGS - command-line args to pass to vim (default none)
#   TMUX_VIM_PANE_WIDTH - how wide a single vim pane is (default 80)
#   TMUX_VIM_PANES - how many vim panes to create
#
# If TMUX_VIM_PANES is not set, then it will be set as large as possible while
# keeping the shell pane width at least TMUX_VIM_SHELL_MIN_WIDTH (default 132)
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# Copyright (c) 2012, Stephen Thirlwall
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# * Redistributions of source code must retain the above copyright
#   notice, this list of conditions and the following disclaimer.
# * Redistributions in binary form must reproduce the above copyright
#   notice, this list of conditions and the following disclaimer in the
#   documentation and/or other materials provided with the distribution.
# * The name of Stephen Thirlwall may not be used to endorse or promote products
#   derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL STEPHEN THIRLWALL BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#------------------------------------------------------------------------------

_tvim_window_id() {
    tmux lsp -a -F '#{pane_id}=#{window_index}' | grep ^$TMUX_PANE= | cut -d= -f2
}

# _tvim_store key value
# - stores key/value pair in tmux environment
# - appends window id to key so this is a per-window setting
# - much thanks to Romain Francoise for help with this!
_tvim_store() {
    tmux set-environment "${1}_$( _tvim_window_id )" "$2"
}

# _tvim_fetch key
# - retrieves value from tmux environment
# - appends window id to key so this is a per-window setting
# - much thanks to Romain Francoise for help with this!
_tvim_fetch() {
    tmux show-environment | grep "^${1}_$( _tvim_window_id )=" | cut -d= -f2-
}

_tvim_fetch_or_store() {
    if [[ $# -gt 1 ]]; then
        _tvim_store "$@"
    else
        _tvim_fetch "$@"
    fi
}

_tvim_pane_id() {
    _tvim_fetch_or_store tmux_vim_pane "$@"
}

_tvim_dir() {
    _tvim_fetch_or_store tmux_vim_dir "$@"
}

_tvim_panes() {
    local shell_min_width=${TMUX_VIM_SHELL_MIN_WIDTH:-132}
    local vim_pane_width=${TMUX_VIM_PANE_WIDTH:-80}
    local screen_width=$( tmux lsc -t $TMUX_PANE -F '#{client_height}' )

    #TODO: change client_height to client_width when tmux 1.7 arrives

    local panes=$[ ( $screen_width - $shell_min_width ) / ( $vim_pane_width + 1 ) ]
    echo $[ $panes > 0 ? $panes : 1 ]
}

_tvim_is_running() {
    local pane_id=$( _tvim_pane_id )
    [[ -n $pane_id ]] && tmux lsp -F '#{pane_id}' | grep -q ^$pane_id$
}

# _tvim_start [number-of-panes]
# - split a new tmux pane and start vim in it
# - the pane id is stored as tvim_pane, using _tvim_store
_tvim_start() {
    if _tvim_is_running; then
        # TVIM already exists - try to select that pane
        tmux select-pane -t $( _tvim_pane_id ) && return

        # If we get here, that pane no longer exists, so fall thru
        # (shouldn't happen)
    fi

    local vim_panes=${1:-${TMUX_VIM_PANES:-$(_tvim_panes)}}
    local vim_pane_width=${TMUX_VIM_PANE_WIDTH:-80}
    local split_width=$[ ($vim_pane_width + 1) * $vim_panes - 1 ]

    local vim_args=$TMUX_VIM_ARGS
    #vim_args+=" -O$vim_panes"  # this is annoying me - turning it off

    # Split a new pane, start vim in it, and record the pane index
    local tvim_pane=$(tmux split-window -P -h -l $split_width \
                        "exec vim $vim_args")

    # Now convert the pane index into a global persistent id
    # 0:1.1: [100x88] [history 0/10000, 0 bytes] %2
    # ^^^^^ $tvim_pane                  pane_id  ^^
    _tvim_pane_id $(tmux lsp -a | grep ^${tvim_pane}: | grep -o '%[0-9]\+')
    _tvim_dir "$PWD"
}

# _tvim_send_keys [keystrokes...]
# - sends keystrokes to the vim instance created by tvim
# - keystroke syntax is the same as tmux send-keys
_tvim_send_keys() {
    tmux send-keys -t $( _tvim_pane_id ) "$@"
}
# _tvim_op <op> <file>
# - does _tvim_send_keys :$op space $file
# - escapes spaces correctly in $file
_tvim_op() {
    # Backslash escape all spaces in the file name
    _tvim_send_keys :$1 space "${2// /\\ }" enter
}

# tvim [files...]
# - if no existing tvim instance is running, a new one is spawned
# - opens the listed files inside the tvim instance
tvim() {
    _tvim_start
    _tvim_send_keys escape  # make sure we're in command mode

    if [[ $# -gt 0 ]]; then

        # If we are now in a different directory than $TDIR, we want to make
        # vim switch to this directory temporarily before opening the files.
        # This obviates any relative path computations.
        [[ "$PWD" != "$( _tvim_dir )" ]] && _tvim_op cd "$PWD"

        # Rather than :edit each file in turn, :badd each file into a new
        # buffer, and then finally switch to the last one with :buffer.
        # This is to handle the situation where the current buffer is unsaved,
        # and an :edit command will cause vim to prompt the user to save,
        # abandon or cancel.
        # If we just :edit each file, things just don't work out naturally;
        # cancel works, but yes/no end up with only the first file opened.
        # Errant escape keys cause the whole open to just silently fail.
        # This approach pushes the user interaction right to the end.
        for file in "$@"; do
            _tvim_op badd "$file"   # load a buffer for each file
        done

        [[ "$PWD" != "$( _tvim_dir )" ]] && _tvim_op cd -

        _tvim_op buffer "${!#}"       # switch to the final file
    fi

    tmux select-pane -t $( _tvim_pane_id )
}

tvim "$@"

